Dionisio hurtado
Nanomarquez/tupcideal pull request #26
Opened 2022-10-15 23:23 UTC by hurtado82

se implemento filtro por marca en componente productos

2022-10-15 23:44 UTC, Francostamagna approved these changes

2022-10-15 23:45 UTC, Francostamagna approved these changes

2022-10-15 23:45 UTC, Francostamagna approved these changes

2022-10-16 16:57 UTC, Robmargar approved these changes

2022-10-16 23:27 UTC, Francostamagna requested changes
El filtrado por brand iria en el back

2022-10-17 19:17 UTC, closed without merging